### ISSUE TITLE
AttributeError: 'DecoderLayer' object has no attribute 'self_attn'

### ISSUE THREAD

**Issue by Electrolls** [spectraldoy/music-transformer#2]
Heya, I faced this error while trying to generate some MIDIs based on your pretrained weights. Do you know how I can fix this? I feel that it's something to do with the PyTorch version but I have installed the versions as listed in requirements.txt.

PS C:\Users\USER\Desktop\music-transformer-main> python generate.py models/chopintransformerv5.pt .../gen_audio.mid -v
Greedy decoding...
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\music-transformer-main\generate.py", line 282, in <module>
    generate(model_=music_transformer, inp=["<start>"], save_path=args.save_path,
  File "C:\Users\USER\Desktop\music-transformer-main\generate.py", line 229, in generate
    token_ids = greedy_decode(model=model_, inp=inp, mode=mode, temperature=temperature, k=k)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\music-transformer-main\generate.py", line 109, in greedy_decode
    predictions = model(inp, mask=create_mask(inp, n))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\music-transformer-main\model.py", line 107, in forward
    x = self.decoder(x, memory=None, tgt_mask=mask)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\transformer.py", line 461, in forward
    seq_len = _get_seq_len(tgt, self.layers[0].self_attn.batch_first)
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DecoderLayer' object has no attribute 'self_attn'

**Comment by Electrolls** [comment]
I found the error, seems that the code only works on Python 3.8 so I had to downgrade it
